steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', '_SERVICE_ACCOUNT_KEY=$_SERVICE_ACCOUNT_KEY', '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME', '.' ]
  secretEnv: ['_SERVICE_ACCOUNT_KEY']

  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '$_APP_NAME', '--image', 'gcr.io/$PROJECT_ID/$_APP_NAME', '--region', 'europe-north1']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebasekey/versions/2
      env: '_SERVICE_ACCOUNT_KEY'
images:
- 'gcr.io/$PROJECT_ID/$_APP_NAME'
timeout: 900s
