steps:
  # build the container image using kaniko with cache
- name: 'gcr.io/kaniko-project/executor:v1.6.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/$_APP_NAME
  - --cache=true
  #- --cache-ttl=26h
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '$_APP_NAME', '--image', 'gcr.io/$PROJECT_ID/$_APP_NAME', '--region', 'europe-north1']

timeout: 3600s
