version: "3.7"

services:
  kitchen:
    container_name: kitchen
    build:
      context: ./
      args:
        - _SERVICE_ACCOUNT_KEY
    image: kitchen:latest
    volumes:
      - ${LOCAL_SERVICE_ACCOUNT_KEY}:/keys/service_account_key.json
      - ./src:/code
    entrypoint: /bin/bash
    command: -c "python3 server_dev.py"
    ports:
      - "8080:8080"
