version: "3.7"

services:
  kitchen:
    container_name: kitchen
    build:
      context: ./
      args:
        - _SERVICE_ACCOUNT_KEY
    image: kitchen:latest
    volumes:
      - ${LOCAL_SERVICE_ACCOUNT_KEY}:/keys/service_account_key.json
      - ./cuisson:/code
    entrypoint: /bin/bash
    command: -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
